version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: categoryeyes
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"